---
x-default-logging: &default-logging
  logging:
    options:
      max-size: '100m'
      max-file: '5'
    driver: json-file

services:
  gateway:
    <<: [ *default-logging ]
    build:
      context: ignition-docker/gw-build
      dockerfile: Dockerfile
      args:
        IGNITION_VERSION: ${IGNITION_VERSION:-8.1.47}
    image: huntermatuse-ignition:dev-${IGNITION_VERSION:-8.1.47}
    ports:
      - 8088:8088
    environment:
      TZ: America/NewYork
      GATEWAY_ADMIN_PASSWORD: ${GATEWAY_PASSWORD:-password}
    volumes:
      - ./ignition:/workdir